src/index.js, src/parser.js, test/fixtures/plural.js, test/parser.js
- Fix Lint errors and warnings when running `npm install`
- Fix plurals using variables not working
=> Fix plural with variables

package.json, src/index.js, src/jsx-parser.js, src/parser.js, test/fixtures/app.jsx, test/jsx-parser.js, test/parser.js
This adds basic support for use of Trans components. There are probably still a few missing pieces, but it seems to work for me.
=> Support react-i18n <Trans> components

package.json, src/jsx-parser.js, test/jsx-parser.js
parse5 will enforce HTML policies, such as forcing empty elements to have no text. This will break valid JSX using components with names like `Link`. To fix this switch to the XML parser mode of htmlparser2.
This fixes #51
=> Use htmlparser2 to parse JSX

package.json
Hello, @cheton 
I'm trying to install the latest release of i18next-scanner without success:
```
$ npm install i18next-scanner
...
npm ERR! enoent ENOENT: no such file or directory, chmod '/tmp/container/node_modules/i18next-scanner/bin/cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/tmp/container/node_modules/i18next-scanner/bin/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```
I could install it if I ignore the bin links:
```
$ npm install i18next-scanner --no-bin-links
```
I think you miss the bin folder to be added to the package :)
I added it but I don't know if we need to test it, or how to test it. Do you have any suggestion?
=> Fix the installation of cli.

src/parser.js, test/parser.js
This PR tries to improve the handling of default values. Specifically it does two things:
* if you use the same key twice, but don't supply a default on the first occurrence any defaultValue set on other instances was ignored.
* if you use a different default value for the same key in multiple places i18next-scanner will warn you.
=> Improve handling of default values

package.json
i18next-scanner/bin/cli.js needs this package.
```javascript
var program = require('commander');
```
=> Add missing dependency 'commander'

package.json
Dependency 'chalk' is not only needed during development time, so moved to 'dependencies'.
=> Move 'chalk' dependency to dependencies instead of devDependencies

src/parser.js, test/fixtures/trans.jsx, test/parser.js, test/transform-stream.js
This PR fixes #90 where translation within props cannot be correctly parsed:
```jsx
<Component render={<Trans>translation from props</Trans>} />
```
=> Iterates through all of the JSX element attributes to filter JSXElement values (#90)

README.md
=> README typo: s/trun/turn/

src/parser.js, test/parser.js
When using trailing comma in a function within the `t` function the scanner throws an error because an empty string is passed to the esprima parser.
This PR includes a test case as well as the fix. Please let me know if you have a better idea on how to fix it or how to implement the test case.
The script is still working as expected without the fix, because the error is catched, but the it logs an error in debug mode which is first annoying and second reduces trust into the library.
=> Fix debug warning in case of trailing comma in function

package.json, src/acorn-jsx-walk.js, src/parser.js, test/fixtures/modules/index.js, test/fixtures/trans-acorn-broken.jsx, test/fixtures/trans-acorn.jsx, test/fixtures/trans.jsx, test/jsx-parser.js, test/parser.js
Currently a very old version of `acorn-jsx` is being used to parse occurences of the `<Trans>` component.
This leads to lots of errors when people use modern JavaScript syntax that cannot be parsed by the ancient `acorn`.
This patch upgrades to the latest `acorn-jsx` version and comes with a custom version of `acorn-jsx-walk` based on `acorn-walk`.
Should fix:
* #86
* #88 
* #93
=> Upgrade to acorn 6

package.json, src/parser.js, test/parser.js
Improved languages plurals support.
=> Languages plurals

.travis.yml, babel.config.js, package.json, src/parser.js
See https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#usebuiltins-entry-with-corejs-3
=> Fix build failure when transpiling testing code with Babel

README.md, src/parser.js, test/fixtures/context-plural.js, test/fixtures/context.js, test/parser.js
This allows scanner to add a proper values for `context` when it is a dynamic values => both of the values (`male`, `female`) should be in the translation file.
Closes https://github.com/i18next/i18next-scanner/issues/176
=> Add support for dynamic context

README.md, src/parser.js, test/transform-stream.js
To allow loadPath and savePath on the resource configuration to be functions so you can have separated language stores. Usable if working with plugins and want to keep language translations separated.
- [ X] only relevant code is changed (make a diff before you submit the PR)
- [ X] run tests `npm run test`
- [X ] tests are included
- [ X] documentation is changed or added
=> feat: allow loadPath and savePath on resource configuration to be functions

README.md
`content` variable is going to be re-assigned, so if we use `const`, we're going to get the following error:
"Uncaught TypeError: Assignment to constant variable."
=> chore: use let instead of const to fix type error

README.md, bin/cli.js, package.json, src/index.js, src/nodes-to-string.js, src/parser.js, test/jsx-parser.test.js, test/parser.test.js, test/transform-stream.test.js
Usage with simple HTML elements like `<br />` and others (v10.4.0)
https://react.i18next.com/latest/trans-component#usage-with-simple-html-elements-like-less-than-br-greater-than-and-others-v10.4.0
=> feat: rework the `nodesToString` function to output expected element tags

.github/workflows/node.js.yml, src/parser.js
This updates the terminal messaging when a conflicting default translation has a mismatch with the translation in the default language json file to include the default message. This is to make it easier to locate which translation is conflicting as there is a chance that there are numerous keys sharing the same name at a deeper level e.g.
```
"user": {
"button": {
"tooltip": "User tooltip"
},
},
"admin": {
"button": {
"tooltip": "Admin tooltip"
},
},
"placeholder": {
"button": {
"tooltip": "Placeholder tooltip"
},
},
```
Before this would output that the key `tooltip` had a conflict, which in larger translation files becomes very difficult to track down.
=> Update conflicting default translation message

src/parser.js
This fixes #156 and #168.
I'm just using the suggested fix for deepMerge.
=> Fix array duplication after parse

src/parser.js
Do not show log message when defaultValue returns undefined because in this case no translation key is added
Fixes https://github.com/i18next/i18next-scanner/issues/245
=> fix: do not show log message when defaultValue returns undefined

README.md, src/parser.js, test/fixtures/trans-component.jsx, test/parser.test.js
Fixes https://github.com/i18next/i18next-scanner/issues/242
=> feat: add possibility to pass RegExp to trans.component

src/parser.js
This PR removes the traverse code in `parseJSXElement` to eliminate redundant calls for setting translation keys. The functionality is now handled by the `acorn-jsxwalk` library, which allows for traversing all `JSXElement` nodes seamlessly.
=> refactor: remove the traverse code in `parseJSXElement` to eliminate redundant calls for setting translation keys

README.md, examples/i18next-scanner.config.js, src/parser.js, test/parser.test.js
Fixes gh-228
Supports new plural suffixes via a new option `pluralVersion` which specifies the `compatibilityJSON` version to use for pluralization. Default behavior remains unchanged.
=> Support new plural suffixes with JSON v4 format

src/parser.js, test/react-i18next/i18n.js, test/react-i18next/trans-render.test.js
Our original problem is that: due to an upgrade of i18next version and a move to typescript, many of our plural uses-cases using the Trans component do not work anymore.
This pull request answers a few translations that are not taken in account with the current parser.
- count={a.b}
- count={a?.b}
- count={a - 1}
- count={a ? b : c}
=> feat(parser): Handle a few more use cases of potential count attributes.

.github/workflows/node.js.yml
GH action is only running on node 14 and 16 - which are both fully outdated and end-of-life.
=> ci: add test with node runtime 18 and 20

README.md, package.json, src/parser.js, test/transform-stream.test.js
=> feat(parser): Add exception for removing unused keys
